version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: shivam_sql_contanier7
    environment:
      MYSQL_DATABASE: shivam_hms_db  
      MYSQL_USER: root 
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - ola_network


  springboot:
    build: .
    container_name: HMS
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shivam-hms-db.crur85fhxixa.ap-southeast-1.rds.amazonaws.com:3306/shivam_hms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678

networks:
  ola_network:
    driver: bridge
